name: Icon test san
description: Temporary Hello world action for testing
author: sa-ny

# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
